language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
jobs:
  include:
    - name: flake8
      python: 3.8
      install: pip install tox
      script: tox -e flake8
      after_success:
install:
  - pip install coverage coveralls coverage-python-version -cconstraints.txt
  - pip install freezegun mock flake8
  - pip install --no-deps -e .
script:
  - coverage run -m gtimelog.tests
after_success:
  - coveralls
notifications:
  email: false
